# SFDT_Ibrahim ğŸš€ AGPL-3.0 License - https://sfdt_ibrahim.com/license

blank_issues_enabled: true
contact_links:
  - name: ğŸ“„ Docs
    url: https://docs.sfdt_ibrahim.com/
    about: Full SFDT_Ibrahim YOLO Documentation
  - name: ğŸ’¬ Forum
    url: https://community.sfdt_ibrahim.com/
    about: Ask on SFDT_Ibrahim Community Forum
  - name: ğŸ§ Discord
    url: https://sfdt_ibrahim.com/discord
    about: Ask on SFDT_Ibrahim Discord
  - name: âŒ¨ï¸ Reddit
    url: https://reddit.com/r/sfdt_ibrahim
    about: Ask on SFDT_Ibrahim Subreddit
